#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

# base excludes
exclude_args=( '*.git*' '.gitignore' 'create-zip.sh' 'deathclock.zip' )

# if this is a git repo, add all currently-ignored paths to the zip exclusion list
if git rev-parse --git-dir >/dev/null 2>&1; then
    while IFS= read -r -d '' f; do
        exclude_args+=("$f")
    done < <(git ls-files -oi --exclude-standard -z)
fi

# create zip of non-hidden files/dirs, excluding ignored files
zip -r9 deathclock.zip * -x "${exclude_args[@]}"